### ISSUE TITLE
Serena fails when `nul` file exists in directory on Windows

### ISSUE THREAD

**Issue by keoy7am** [oraios/serena#506]
Serena encounters a fatal error when a file named nul exists in the project directory on Windows systems. The nul
   file appears to be created by certain IDEs (exact source unknown), and its presence causes path resolution
  failures due to Windows treating nul as a reserved device name.

  Environment

  - OS: Windows
  - UV: 0.8.12 (36151df0e 2025-08-18)
  - Python: 3.12.2 (tags/v3.12.2:6abddd9, Feb 6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]

  Steps to Reproduce

  1. Have a nul file present in the project directory
  2. Run serena project index or serena health-check
  3. Observe the ValueError

  Expected Behavior

  Serena should handle Windows reserved filenames gracefully, either by:
  - Skipping files with reserved names
  - Providing a clear warning message
  - Continuing operation without crashing

  Actual Behavior

  The application crashes with a ValueError when attempting to resolve relative paths involving the nul file.

---

  Error Logs

<details>
  <summary>Execute Project Index</summary>

```
  Indexing symbols in project A:\2. TestProjects\1. SerenaTest\ProjectIndex
  Traceback (most recent call last):
    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Scripts\serena.exe\__main__.py",
  line 10, in <module>
      sys.exit(top_level())
               ~~~~~~~~~^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 1442, in __call__
      return self.main(*args, **kwargs)
             ~~~~~~~~~^^^^^^^^^^^^^^^^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 1363, in main
      rv = self.invoke(ctx)
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 1830, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 1830, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
                             ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 1226, in invoke
      return ctx.invoke(self.callback, **ctx.params)
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\click\core.py",
  line 794, in invoke
      return callback(*args, **kwargs)
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\serena\cli.py",
  line 439, in index
      ProjectCommands._index_project(project, log_level, timeout=timeout)
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\serena\cli.py",
  line 462, in _index_project
      files = proj.gather_source_files()
    File "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\serena\pro
  ject.py", line 198, in gather_source_files
      rel_file_path = os.path.relpath(os.path.join(root, file), start=self.project_root)
    File "<frozen ntpath>", line 796, in relpath
  ValueError: path is on mount '\\\\.\\nul', start on mount 'A:'
```

</details>

<details>
  <summary>Health Check</summary>

```
  ERROR 2025-08-21 01:26:34,444 serena.cli:health_check:665 - Health check failed with exception: path is on mount
  '\\\\.\\nul', start on mount 'A:'
  Traceback (most recent call last):
    File
  "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\serena\cli.py",
  line 561, in health_check
      files = proj.gather_source_files()
    File "C:\Users\WindowsUser\AppData\Local\uv\cache\archive-v0\uwSETn4veLVV9UEm820HC\Lib\site-packages\serena\pro
  ject.py", line 198, in gather_source_files
      rel_file_path = os.path.relpath(os.path.join(root, file), start=self.project_root)
    File "<frozen ntpath>", line 796, in relpath
  ValueError: path is on mount '\\\\.\\nul', start on mount 'A:'
  ❌ Health check failed: path is on mount '\\\\.\\nul', start on mount 'A:'
```

</details>

  Additional Context

  The issue occurs because Windows treats nul as a reserved device name (along with con, prn, aux, com1-com9,
  lpt1-lpt9). When os.path.relpath() encounters this special file, it interprets it as a device mount point
  (\\\\.\\nul) rather than a regular file, causing the path resolution to fail.

  Workaround

  Manually delete or rename the nul file from the project directory before running Serena commands.

**Comment by MischaPanch** [comment]
I think the workaround is quite good. Is there a reason one should have a nul file in a project dir if this is a special name?

**Comment by opcode81** [comment]
An analogous problem was addressed in #330

**Comment by keoy7am** [comment]
Looks like someone has found the source of the nul file that's been bothering me for a while. [#330 ](https://github.com/oraios/serena/issues/330#issuecomment-3108446661)
It seems that the fix did not work correctly at the time.

Based on the [commit](https://github.com/oraios/serena/commit/f2b01a05738d6910abd233a98fe391747c97feaa) and the latest [code](https://github.com/oraios/serena/blob/8464f257aafaa5b66b63aae6921bdcc800c90b4e/src/serena/project.py#L198), it seems the issue still cannot be resolved.

Perhaps the line of code [rel_file_path](https://github.com/oraios/serena/blob/8464f257aafaa5b66b63aae6921bdcc800c90b4e/src/serena/project.py#L198) should be placed within a try-except block (the same logic should apply consistently in similar situations).

**Comment by MischaPanch** [comment]
#471 is somewhat related. The author has closed it for an unknown reason, but it's a reasonable fix IMO (see my comments there)

**Comment by opcode81** [comment]
> It seems that the fix did not work correctly at the time.

What makes you think that? It does work correctly, but there are other calls to `relpath` which can result in the same problem.

> https://github.com/oraios/serena/pull/471 is somewhat related. The author has closed it for an unknown reason, but it's a reasonable fix IMO (see my comments there)

No, #471 does not solve the problem. The nul file causes `relpath` to raise an exception, and the function is still being applied in a manner that will fail.

**Comment by MischaPanch** [comment]
I'm not saying #471 solves the problem, but the fix for this should probably also take care of the concern of #471 - like a centralized and safe util for getting relative paths

**Comment by opcode81** [comment]
@MischaPanch, we should address the problem of the code being improperly factorised; I mentioned this before.

Why do we have both `is_ignored_path` and `is_ignored_relative_path` without one calling the other? It doesn't make sense to me.
If the functions were properly factorised, then `gather_source_files` wouldn't need to call `relpath` in the first place.

**Comment by MischaPanch** [comment]
yes, it's a technical debt, let's fix it.

**Comment by opcode81** [comment]
imo the fix for #471 is to completely remove `_is_ignored_dirname`. It makes the completely random assumption that a directory whose name starts with a `.` must be ignored. There is no grounds for this.

Such decisions must be made explicitly by the user. We cannot just assume that such directories should be ignored.

Perhaps interestingly, `is_ignored_path` makes the (perhaps reasonable) assumption that `.git` should be ignored, while `is_ignored_relative_path` will ignore any path that contains a directory whose name starts with ".".

**Comment by MischaPanch** [comment]
Let's have a call on that, we have some possibly related issues in #470. We should make sure we never scan through too large directories, even for finding out whether there are .gitignore files.

**Comment by opcode81** [comment]
> Why do we have both is_ignored_path and is_ignored_relative_path without one calling the other? It doesn't make sense to me.
If the functions were properly factorised, then gather_source_files wouldn't need to call relpath in the first place.

You already fixed this 👍. I was on an older commit where it wasn't yet.

**Comment by opcode81** [comment]
I have added a PR which should fix this (and a few other related issues).

**Comment by Guthman** [comment]
I'm still encountering this issue.

`Starting Serena server (version=0.1.4-7274b22e-dirty, process id=26208, parent process id=50040; language backend=JETBRAINS)`

Error:
```
INFO  2026-01-07 09:46:07,946 [MainThread] mcp.server.lowlevel.server:_handle_request:709 - Processing request of type CallToolRequest
INFO  2026-01-07 09:46:07,946 [MainThread] serena.task_executor:issue_task:192 - Scheduling Task-14:FindFileTool
INFO  2026-01-07 09:46:08,018 [SerenaAgentTaskExecutor] serena.task_executor:_process_task_queue:123 - Starting execution of Task-14:FindFileTool
INFO  2026-01-07 09:46:08,019 [Task-14:FindFileTool] serena.task_executor:start:360 - Task-14:FindFileTool starting ...
INFO  2026-01-07 09:46:08,019 [Task-14:FindFileTool] serena.tools.tools_base:_log_tool_application:205 - find_file: file_mask='setup.py', relative_path='.'
ERROR 2026-01-07 09:46:08,313 [Task-14:FindFileTool] serena.tools.tools_base:task:274 - Error executing tool: path is on mount '\\\\.\\NUL', start on mount 'D:'
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\uv\cache\archive-v0\ZY1vwKMQDpdUoXQZIjhDx\Lib\site-packages\serena\tools\tools_base.py", line 249, in task
    result = apply_fn(**kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\uv\cache\archive-v0\ZY1vwKMQDpdUoXQZIjhDx\Lib\site-packages\serena\tools\file_tools.py", line 149, in apply
    _dirs, files = scan_directory(
                   ^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\uv\cache\archive-v0\ZY1vwKMQDpdUoXQZIjhDx\Lib\site-packages\serena\util\file_system.py", line 55, in scan_directory
    result_path = os.path.relpath(entry_path, rel_base)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 796, in relpath
ValueError: path is on mount '\\\\.\\NUL', start on mount 'D:'
```
